apiVersion: v1
kind: Service
metadata:
  name: aakash-alpha-svc
  labels:
    app: aakash-alpha
spec:
  type: LoadBalancer
  selector:
    app: aakash-alpha
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
